agent_name: mindshare_agent
author: xiuxiuxar
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.55.0, <3.0.0'
fingerprint:
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeigz2b62yc6haiqcjwssmkb4blb6d64t4i7u53g56cacq4w3b3x5mq
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeiatbbjb36uvzzc2pnnrqpdk2xlaic5zwsxj6frswqhw6illauqg6e
- eightballer/http_server:0.1.0:bafybeifilny6luzcs4dtv5d2ta4fqqgi7aixch7f75sqnwcqh73oxcgtdu
- eightballer/prometheus:0.1.1:bafybeig7p3tzs7x4awcxjr7ctxljr6h7mrc2c36thnab6zoteualgivj6e
- valory/ledger:0.19.0:bafybeierez3cyecdieur34h2wc7wgaqnzfxm6nv5uhxkujlyqdap4wkjvi
- eightballer/dcxt:0.1.0:bafybeihj2ko7bwqmxiudoixrlzwml5snurdxaiomfl4lrbbcat3k5sxnxy
contracts:
- eightballer/erc_20:0.1.0:bafybeiewlvc62xn6flmzn2dodqw3w6p3w5jqwkx36w5caznf6zjph7t2se
- valory/erc20:0.1.0:bafybeihzzfy7hhegokwbzuwfqdzx2ck3jvg4ccb53fpy4btq7so3f4nezq
- valory/multisend:0.1.0:bafybeicgoayj3nfrslr5ilcvmytdlc62ebtef2yzc5iq72ivbvgykv26wm
- valory/gnosis_safe:0.1.0:bafybeigsekgqjoi5phewoqfoqwzsxei4qwfv6n5rapzhd75pvamypvwohe
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeibbzlmexojfots3kddaglfg2a4ieyebly7wnb2gismqxsosp5f6oi
- valory/staking_token:0.1.0:bafybeif3d753nt6um3qrdtrytmlyqd7ao7spio6yits3qymuj62y3h2jri
protocols:
- valory/contract_api:1.0.0:bafybeidpch6cvuweq5x4h6ummnnw5xynmfsbj3sxm2m63seuqizrmvpd3e
- eightballer/default:0.1.0:bafybeibu3dme3plwprq5j6xl6vfx2e5ebwbudtj5yndkxcsoiwxljst22a
- eightballer/http:0.1.0:bafybeicpvdcuz5wqgnzqzqyyh3ifo63pqjhze6escra4dxqpxbaz5qs2jy
- eightballer/prometheus:1.0.0:bafybeiedkmjjqbxyid67hwhpkvyknst5rdtn5pazs6rtaa3mj6r2buwl7q
- open_aea/signing:1.0.0:bafybeign4u6o3jtz2kuelpuhrmzosbyix2iwf7ifxythigrcuef4ybmuna
- eightballer/tickers:0.1.0:bafybeifiytrsffwnhhilbavse623qsil3tulizbazf7cd7ghfepriejgkq
- eightballer/orders:0.1.0:bafybeid24shv2uqltnnxn72p6upjb7qzq3lew7fgre2dno72ui5oolvbee
- valory/ledger_api:1.0.0:bafybeic5qfhodpwqjdkwxs4gzummpc3dxbpn4egg7s7f2gibfopa4nxz4i
skills:
- eightballer/prometheus:0.1.0:bafybeibfuwvdxxnxnm2gghg4t2c7ucdxhmu2xlrpdkk46t5rx7qskbx7ui
- xiuxiuxar/mindshare_app:0.1.0:bafybeierocv437kk7oei6fml67mdywiibifnnieve6caexalmo5ihhw76y
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
      markup: true
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  eth-abi:
    version: ==5.1.0
  eth-utils:
    version: '>=2.3.1'
  eth-typing:
    version: <=5.2.0
  hexbytes:
    version: '>=1.3.1,<2.0.0'
  open-autonomy: {}
  open-aea-ledger-ethereum:
    version: ==2.0.5
  open-aea-test-autonomy: {}
  packaging:
    version: '>=23.1,<24.0'
  pycryptodome:
    version: ==3.20.0
  requests:
    version: '>=2.28.1,<2.31.2'
  web3:
    version: '>=7,<8'
  pandas:
    version: ==2.3.2
  httpx: {}
  pandas-ta-classic:
    version: ==0.3.14b2
  open-aea-ledger-cosmos:
    version: ==2.0.5
  rich:
    version: '>=14.1.0,<15.0.0'
  cowdao-cowpy: {}
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: ${str:0.0.0.0}
  port: ${int:8716}
  target_skill_id: xiuxiuxar/mindshare_app:0.1.0
---
public_id: xiuxiuxar/mindshare_app:0.1.0
type: skill
models:
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      coingecko_api_key: ${str:test_key}
      trendmoon_api_key: ${str:test_key}
      coingecko_rate_limit_per_minute: ${int:25}
      coingecko_monthly_credits: ${int:10000}
      trendmoon_rate_limit_per_minute: ${int:25}
      trendmoon_rate_limit_per_second: ${int:5}
      trendmoon_monthly_credits: ${int:10000}
      staking_chain: ${str:base}
      staking_threshold_period: ${int:5}
      min_num_of_safe_tx_required: ${int:1}
      staking_token_contract_address: ${str:0x8b8a86A056D3145Ec2ecc30FB52C3aF2e6daB7C5}
      on_chain_service_id: ${int:41}
      service_id: ${str:mindshare}
      data_sufficiency_threshold: ${float:0.8}
      max_exposure_per_position: ${float:20.0}
      max_positions: ${int:7}
      max_total_exposure: ${float:80.0}
      buffer_ratio: ${float:0.05}
      min_position_size_usd: ${float:10.0}
      reset_pause_duration: ${int:300}
      safe_contract_addresses: ${str:{"ethereum":"0x0000000000000000000000000000000000000000","base":"0x0000000000000000000000000000000000000000"}}
      store_path: ${str:/data}
      stop_loss_pct: ${float:0.84}
      trading_strategy: ${str:balanced}
      trailing_stop_loss_activation_level: ${float:1.25}
      trailing_stop_loss_pct: ${float:0.97}
      moving_average_length: ${int:20}
      rsi_period_length: ${int:14}
      rsi_lower_limit: ${int:39}
      rsi_upper_limit: ${int:66}
      rsi_overbought_limit: ${int:79}
      macd_fast_period: ${int:12}
      macd_slow_period: ${int:26}
      macd_signal_period: ${int:9}
      adx_period_length: ${int:14}
      adx_threshold: ${int:41}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    base:
      address: ${str:https://base.drpc.org}
      chain_id: 8453
      poa_chain: false
      default_gas_price_strategy: eip1559
      gas_price_strategies:
        eip1559:
          max_gas_fast: 1500
          fee_history_blocks: 10
          fee_history_percentile: 5
          min_allowed_tip: 1000000000
          fallback_estimate:
            maxFeePerGas: 20000000000
            maxPriorityFeePerGas: 3000000000
      is_gas_estimation_enabled: true
      timeout: 10
    ethereum:
      address: ${str:https://base.drpc.org}
      chain_id: 8453
      poa_chain: false
      default_gas_price_strategy: eip1559
      gas_price_strategies:
        eip1559:
          max_gas_fast: 1500
          fee_history_blocks: 10
          fee_history_percentile: 5
          min_allowed_tip: 1000000000
          fallback_estimate:
            maxFeePerGas: 20000000000
            maxPriorityFeePerGas: 3000000000
      is_gas_estimation_enabled: true
      timeout: 10
---
public_id: eightballer/dcxt:0.1.0:bafybeihj2ko7bwqmxiudoixrlzwml5snurdxaiomfl4lrbbcat3k5sxnxy
type: connection
config:
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    etherscan_api_key: ${str:test_key}
    rpc_url: ${str:https://base.drpc.org}
  - name: cowswap
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    etherscan_api_key: ${str:test_key}
    rpc_url: ${str:https://base.drpc.org}
---
public_id: eightballer/http_client:0.1.0
type: connection
config:
  host: ${str:api.coingecko.com}
  port: ${int:443}
