name: mindshare_agent
author: xiuxiuxar
version: 0.1.0
description: A new service, scaffolded by the Adev cli from xiuxiuxar/mindshare_agent:0.1.0
aea_version: '>=1.0.0, <3.0.0'
license: apache-2.0
fingerprint:
  __init__.py: bafybeifdc5tk6topwmcviejgkm3lmrhnhk6fqqvh76hv7xwg3qkhxifznm
  tests/__init__.py: bafybeiausykbndof27hjfgwqg6nnmk7zw7lyytwzekih3gszwdypbtxjka
  tests/test_service.py: bafybeicplirjoql5q3l5zjl5xrgamnoxuj3year7u2vrtfnzzllzeyutuy
fingerprint_ignore_patterns: []
agent: xiuxiuxar/mindshare_agent:0.1.0:bafybeigh6iccw4656acmqs2v2aheclkkpbnasdnuvojc5ogjy4vbat5yx4
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8716
  target_skill_id: xiuxiuxar/mindshare_app:0.1.0
---
public_id: eightballer/dcxt:0.1.0:bafybeihj2ko7bwqmxiudoixrlzwml5snurdxaiomfl4lrbbcat3k5sxnxy
type: connection
config:
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    etherscan_api_key: ${CONNECTION_DCXT_CONFIG_EXCHANGES_0_ETHERSCAN_API_KEY:str:test_key}
    rpc_url: ${BASE_LEDGER_RPC:str:https://base.drpc.org}
  - name: cowswap
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    etherscan_api_key: ${CONNECTION_DCXT_CONFIG_EXCHANGES_0_ETHERSCAN_API_KEY:str:test_key}
    rpc_url: ${BASE_LEDGER_RPC:str:https://base.drpc.org}
---
public_id: valory/ledger:0.19.0:bafybeihgkny2vpdn6uz5zf7lcyws4hsxirndoubeptevjzzsl4ues465am
type: connection
config:
  ledger_apis:
    base:
      address: ${BASE_LEDGER_RPC:str:https://base.drpc.org}
      chain_id: 8453
      poa_chain: false
      default_gas_price_strategy: eip1559
      gas_price_strategies:
        eip1559:
          max_gas_fast: 1500
          fee_history_blocks: 10
          fee_history_percentile: 5
          min_allowed_tip: 1000000000
          fallback_estimate:
            maxFeePerGas: 20000000000
            maxPriorityFeePerGas: 3000000000
      is_gas_estimation_enabled: true
      timeout: 10
    ethereum:
      address: ${BASE_LEDGER_RPC:str:https://base.drpc.org}
      chain_id: 8453
      poa_chain: false
      default_gas_price_strategy: eip1559
      gas_price_strategies:
        eip1559:
          max_gas_fast: 1500
          fee_history_blocks: 10
          fee_history_percentile: 5
          min_allowed_tip: 1000000000
          fallback_estimate:
            maxFeePerGas: 20000000000
            maxPriorityFeePerGas: 3000000000
      is_gas_estimation_enabled: true
      timeout: 10
---
public_id: xiuxiuxar/mindshare_app:0.1.0
type: skill
models:
  params:
    args:
      store_path: ${STORE_PATH:str:./persistent_data}
      safe_contract_addresses: ${SAFE_CONTRACT_ADDRESSES:str:{"ethereum":"0x0000000000000000000000000000000000000000","base":"0x0000000000000000000000000000000000000000"}}
      coingecko_api_key: ${SKILL_MINDSHARE_APP_MODELS_PARAMS_ARGS_COINGECKO_API_KEY:str:test_key}
      trendmoon_api_key: ${SKILL_MINDSHARE_APP_MODELS_PARAMS_ARGS_TRENDMOON_API_KEY:str:test_key}
      reset_pause_duration: ${SKILL_MINDSHARE_APP_MODELS_PARAMS_ARGS_RESET_PAUSE_DURATION:int:10}
