name: mindshare_agent
author: xiuxiuxar
version: 0.1.0
description: A new service, scaffolded by the Adev cli from xiuxiuxar/mindshare_agent:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint:
  __init__.py: bafybeifdc5tk6topwmcviejgkm3lmrhnhk6fqqvh76hv7xwg3qkhxifznm
  tests/__init__.py: bafybeiausykbndof27hjfgwqg6nnmk7zw7lyytwzekih3gszwdypbtxjka
  tests/test_service.py: bafybeicplirjoql5q3l5zjl5xrgamnoxuj3year7u2vrtfnzzllzeyutuy
fingerprint_ignore_patterns: []
agent: xiuxiuxar/mindshare_agent:0.1.0:bafybeihpv4zglsdjmdnjflq66gucwdj2ye2c5b5sfyseaozonsyipkapbq
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: xiuxiuxar/mindshare_app:0.1.0
